apiVersion: triliovault.trilio.io/v1
kind: Restore
metadata:
  name: mongodb-inplace-restore
  namespace: trilio-demo
spec:
  source:
    type: Backup
    backup:
      name: mongodb-demo-backup
      namespace: trilio-demo
  excludeResources:
    - apiVersion: v1
      kind: ConfigMap
      name: odh-kserve-custom-ca-bundle
  cleanupConfig:
    enabled: true
    gracefulDeletionTimeoutSeconds: 120
