apiVersion: batch/v1
kind: Job
metadata:
  name: mongodb-writer
  labels:
    app: mongodb-writer
    demo: trilio-db-demo
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 600
  template:
    metadata:
      labels:
        app: mongodb-writer
        demo: trilio-db-demo
    spec:
      restartPolicy: Never
      containers:
        - name: writer
          image: docker.io/library/mongo:8.0
          command: ["/bin/bash", "/scripts/writer.sh"]
          env:
            - name: DB_HOST
              value: "mongodb-service"
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: MONGO_INITDB_ROOT_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: MONGO_INITDB_ROOT_PASSWORD
            - name: MONGO_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: MONGO_DATABASE
          resources:
            requests:
              cpu: 50m
              memory: 256Mi
            limits:
              cpu: 200m
              memory: 512Mi
          volumeMounts:
            - name: scripts
              mountPath: /scripts
      volumes:
        - name: scripts
          configMap:
            name: mongodb-writer-script
            defaultMode: 0755
