apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
type: Opaque
stringData:
  MARIADB_ROOT_PASSWORD: RootDemo1234!
  MARIADB_USER: demouser
  MARIADB_PASSWORD: Demo1234!
  MARIADB_DATABASE: demodb
