apiVersion: batch/v1
kind: Job
metadata:
  name: sqlserver-writer
  labels:
    app: sqlserver-writer
    demo: trilio-db-demo
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 600
  template:
    metadata:
      labels:
        app: sqlserver-writer
        demo: trilio-db-demo
    spec:
      restartPolicy: Never
      serviceAccountName: sqlserver
      containers:
        - name: writer
          image: mcr.microsoft.com/mssql/server:2022-latest
          command: ["/bin/bash", "/scripts/writer.sh"]
          env:
            - name: DB_HOST
              value: "sqlserver-service"
            - name: SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sqlserver-secret
                  key: SA_PASSWORD
            - name: MSSQL_DATABASE
              value: "demodb"
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
          volumeMounts:
            - name: scripts
              mountPath: /scripts
      volumes:
        - name: scripts
          configMap:
            name: sqlserver-writer-script
            defaultMode: 0755
