---
apiVersion: v1
kind: Service
metadata:
  name: sqlserver-headless
  labels:
    app: sqlserver
spec:
  clusterIP: None
  selector:
    app: sqlserver
  ports:
    - port: 1433
      name: sqlserver
---
apiVersion: v1
kind: Service
metadata:
  name: sqlserver-service
  labels:
    app: sqlserver
spec:
  selector:
    app: sqlserver
  ports:
    - port: 1433
      targetPort: 1433
      name: sqlserver
